export const CROP_COMPAT: Record<string, { good: string[]; bad: string[] }> = {
  tomato:    { good: ['basil','carrot','parsley','garlic'], bad: ['potato','fennel','beet'] },
  cucumber:  { good: ['dill','pea','corn','lettuce'], bad: ['tomato','potato','garlic'] },
  potato:    { good: ['corn','cabbage','garlic','horseradish'], bad: ['tomato','cucumber','sunflower','raspberry'] },
  carrot:    { good: ['onion','lettuce','tomato','pea'], bad: ['dill','parsley','beet'] },
  onion:     { good: ['carrot','beet','lettuce','strawberry'], bad: ['pea','bean'] },
  garlic:    { good: ['tomato','strawberry','carrot','beet'], bad: ['pea','bean','cabbage'] },
  cabbage:   { good: ['dill','potato','onion','beet'], bad: ['tomato','strawberry','garlic'] },
  pepper:    { good: ['basil','carrot','parsley'], bad: ['potato','fennel'] },
  beet:      { good: ['onion','cabbage','lettuce'], bad: ['carrot','tomato','garlic'] },
  strawberry:{ good: ['garlic','onion','lettuce','spinach'], bad: ['cabbage','fennel'] },
  pea:       { good: ['carrot','corn','cucumber','radish'], bad: ['onion','garlic'] },
  corn:      { good: ['pea','cucumber','potato','squash'], bad: ['tomato'] },
  dill:      { good: ['cucumber','cabbage','onion'], bad: ['carrot','tomato'] },
  basil:     { good: ['tomato','pepper'], bad: ['cucumber'] },
  lettuce:   { good: ['carrot','onion','strawberry','cucumber'], bad: [] },
  radish:    { good: ['pea','lettuce','cucumber'], bad: ['hyssop'] },
  zucchini:  { good: ['corn','pea','dill'], bad: ['potato'] },
  pumpkin:   { good: ['corn','pea','dill'], bad: ['potato'] },
}
