import type { Plan } from '../types'

// ============= Время созревания культур =============
export const CROP_DAYS: Record<string, number> = {
  tomato: 90,
  cucumber: 55,
  carrot: 70,
  potato: 80,
  onion: 90,
  garlic: 90,
  cabbage: 80,
  pepper: 100,
  eggplant: 100,
  zucchini: 55,
  beet: 70,
  dill: 40,
  parsley: 60,
  lettuce: 45,
  radish: 30,
  turnip: 60,
  daikon: 60,
  parsnip: 90,
  celery_root: 120,
  pumpkin: 100,
  corn: 80,
  pea: 60,
  spinach: 40,
  arugula: 35,
  basil: 50,
  strawberry: 60,
  raspberry: 365,
  currant: 365,
  gooseberry: 365,
  blackberry: 365,
  blueberry: 365,
  honeysuckle: 365,
  seabuckthorn: 365,
  mint: 60,
  melissa: 60,
  tarragon: 60,
  sorrel: 60,
}

// ============= Категории культур =============
export const CROP_CATEGORIES = [
  {
    id: 'vegetables',
    label: '🥦 Овощи',
    crops: [
      { id: 'tomato', icon: '🍅', name: 'Томат' },
      { id: 'cucumber', icon: '🥒', name: 'Огурец' },
      { id: 'pepper', icon: '🫑', name: 'Перец' },
      { id: 'eggplant', icon: '🍆', name: 'Баклажан' },
      { id: 'zucchini', icon: '🥗', name: 'Кабачок' },
      { id: 'pumpkin', icon: '🎃', name: 'Тыква' },
      { id: 'cabbage', icon: '🥬', name: 'Капуста' },
      { id: 'onion', icon: '🧅', name: 'Лук' },
      { id: 'garlic', icon: '🧄', name: 'Чеснок' },
      { id: 'corn', icon: '🌽', name: 'Кукуруза' },
      { id: 'pea', icon: '🟢', name: 'Горох' },
    ],
  },
  {
    id: 'roots',
    label: '🥕 Корнеплоды',
    crops: [
      { id: 'carrot', icon: '🥕', name: 'Морковь' },
      { id: 'potato', icon: '🥔', name: 'Картофель' },
      { id: 'beet', icon: '🔴', name: 'Свёкла' },
      { id: 'radish', icon: '🌰', name: 'Редис' },
      { id: 'turnip', icon: '🟣', name: 'Репа' },
      { id: 'daikon', icon: '⚪', name: 'Редька' },
      { id: 'parsnip', icon: '🤍', name: 'Пастернак' },
      { id: 'celery_root', icon: '🟤', name: 'Сельдерей' },
    ],
  },
  {
    id: 'greens',
    label: '🌿 Зелень',
    crops: [
      { id: 'dill', icon: '🌿', name: 'Укроп' },
      { id: 'parsley', icon: '🌱', name: 'Петрушка' },
      { id: 'lettuce', icon: '🥗', name: 'Салат' },
      { id: 'spinach', icon: '🍃', name: 'Шпинат' },
      { id: 'arugula', icon: '🌿', name: 'Руккола' },
      { id: 'basil', icon: '🌱', name: 'Базилик' },
    ],
  },
  {
    id: 'perennials',
    label: '🍓 Многолетние',
    crops: [
      { id: 'strawberry', icon: '🍓', name: 'Клубника' },
      { id: 'raspberry', icon: '🫐', name: 'Малина' },
      { id: 'currant', icon: '🍇', name: 'Смородина' },
      { id: 'gooseberry', icon: '🟢', name: 'Крыжовник' },
      { id: 'blackberry', icon: '🫐', name: 'Ежевика' },
      { id: 'blueberry', icon: '🔵', name: 'Голубика' },
      { id: 'honeysuckle', icon: '🌸', name: 'Жимолость' },
      { id: 'seabuckthorn', icon: '🟠', name: 'Облепиха' },
      { id: 'mint', icon: '🌿', name: 'Мята' },
      { id: 'melissa', icon: '🌱', name: 'Мелисса' },
      { id: 'tarragon', icon: '🌿', name: 'Эстрагон' },
      { id: 'sorrel', icon: '🍃', name: 'Щавель' },
    ],
  },
]

// Плоский список всех культур
export const CROPS = CROP_CATEGORIES.flatMap(cat => cat.crops)

// ============= Операции для культур =============
export const CROP_OPERATIONS: Record<string, { id: string; label: string }[]> = {
  tomato:      [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pinching', label: '✂️ Пасынкование' }, { id: 'tying', label: '🪢 Подвязка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  cucumber:    [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pinching_tip', label: '✂️ Прищипка' }, { id: 'tying', label: '🪢 Подвязка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  pepper:      [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pinching', label: '✂️ Пасынкование' }, { id: 'tying', label: '🪢 Подвязка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  eggplant:    [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pinching', label: '✂️ Пасынкование' }, { id: 'tying', label: '🪢 Подвязка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  potato:      [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'hilling', label: '⛏️ Окучивание' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  carrot:      [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  beet:        [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  cabbage:     [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'hilling', label: '⛏️ Окучивание' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  onion:       [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  garlic:      [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  zucchini:    [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pinching_tip', label: '✂️ Прищипка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  pumpkin:     [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pinching_tip', label: '✂️ Прищипка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  pea:         [{ id: 'watering', label: '💧 Полив' }, { id: 'support', label: '🪴 Опора' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  corn:        [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  dill:        [{ id: 'watering', label: '💧 Полив' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  parsley:     [{ id: 'watering', label: '💧 Полив' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  lettuce:     [{ id: 'watering', label: '💧 Полив' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  spinach:     [{ id: 'watering', label: '💧 Полив' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  arugula:     [{ id: 'watering', label: '💧 Полив' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  basil:       [{ id: 'watering', label: '💧 Полив' }, { id: 'pinching', label: '✂️ Прищипка' }, { id: 'disease', label: '⚠️ Болезни' }],
  radish:      [{ id: 'watering', label: '💧 Полив' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  turnip:      [{ id: 'watering', label: '💧 Полив' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  daikon:      [{ id: 'watering', label: '💧 Полив' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  parsnip:     [{ id: 'watering', label: '💧 Полив' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  celery_root: [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  strawberry:  [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pinching_mustache', label: '✂️ Усы' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
  raspberry:   [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pruning', label: '✂️ Обрезка' }, { id: 'tying', label: '🪢 Подвязка' }, { id: 'disease', label: '⚠️ Болезни' }],
  currant:     [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pruning', label: '✂️ Обрезка' }, { id: 'disease', label: '⚠️ Болезни' }],
  gooseberry:  [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pruning', label: '✂️ Обрезка' }, { id: 'disease', label: '⚠️ Болезни' }],
  blackberry:  [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pruning', label: '✂️ Обрезка' }, { id: 'tying', label: '🪢 Подвязка' }, { id: 'disease', label: '⚠️ Болезни' }],
  blueberry:   [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pruning', label: '✂️ Обрезка' }, { id: 'disease', label: '⚠️ Болезни' }],
  honeysuckle: [{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pruning', label: '✂️ Обрезка' }, { id: 'disease', label: '⚠️ Болезни' }],
  seabuckthorn:[{ id: 'watering', label: '💧 Полив' }, { id: 'feeding', label: '🌿 Подкормка' }, { id: 'pruning', label: '✂️ Обрезка' }, { id: 'disease', label: '⚠️ Болезни' }],
  mint:        [{ id: 'watering', label: '💧 Полив' }, { id: 'disease', label: '⚠️ Болезни' }],
  melissa:     [{ id: 'watering', label: '💧 Полив' }, { id: 'disease', label: '⚠️ Болезни' }],
  tarragon:    [{ id: 'watering', label: '💧 Полив' }, { id: 'disease', label: '⚠️ Болезни' }],
  sorrel:      [{ id: 'watering', label: '💧 Полив' }, { id: 'weeding', label: '🌾 Прополка' }, { id: 'disease', label: '⚠️ Болезни' }],
}

// ============= Уведомления =============
export const NOTIF_CHANNELS = [
  { id: 'email', icon: '✉️', label: 'Email' },
  { id: 'vk', icon: '💙', label: 'ВКонтакте' },
]

// ============= Растущие объекты =============
export const GROW_OPTIONS = [
  { id: 'open', icon: '🌱', title: 'Открытый грунт', sub: 'Грядки, огород' },
  { id: 'greenhouse', icon: '🏠', title: 'Теплица', sub: 'Стационарная или плёночная' },
  { id: 'hotbed', icon: '🫧', title: 'Парник', sub: 'Дуги, мини-парник' },
]

// ============= Типы почвы =============
export const SOIL_LABELS: Record<string, string> = {
  loam: 'Суглинок',
  clay: 'Глинистая',
  sandy: 'Песчаная',
  peat: 'Торфяная',
  black: 'Чернозём',
  ready: 'Покупной грунт',
  coconut: 'Кокосовый',
  hydro: 'Гидропоника',
  own: 'Своя смесь',
}

// ============= Операции по умолчанию =============
export const DEFAULT_OPS = [
  { id: 'watering', label: '💧 Полив' },
  { id: 'weeding', label: '🌾 Прополка' },
  { id: 'disease', label: '⚠️ Болезни' },
]

// ============= Сорта культур (рекомендуемые) =============
export const CROP_VARIETIES: Record<string, { name: string; days: number; desc?: string }[]> = {
  tomato: [
    { name: 'Бычье сердце', days: 110, desc: 'Крупноплодный, мясистый' },
    { name: 'Черри', days: 85, desc: 'Мелкий, сладкий, урожайный' },
    { name: 'Де Барао', days: 120, desc: 'Высокорослый, лёжкий' },
    { name: 'Белый налив', days: 85, desc: 'Ранний, неприхотливый' },
    { name: 'Сливка', days: 90, desc: 'Для консервации' },
    { name: 'Ультраскороспелый', days: 75, desc: 'Для открытого грунта севера' },
    { name: 'Розовый мёд', days: 100, desc: 'Розовые, очень сладкие' },
    { name: 'Чёрный принц', days: 105, desc: 'Тёмно-бордовый, насыщенный' },
    { name: 'Президент', days: 95, desc: 'Крупный, транспортабельный' },
    { name: 'Финик', days: 90, desc: 'Гроздевой, длительное плодоношение' },
  ],
  cucumber: [
    { name: 'Родничок', days: 45, desc: 'Классический, проверенный' },
    { name: 'Герман', days: 42, desc: 'Партенокарпик, для теплицы' },
    { name: 'Муромский', days: 38, desc: 'Ранний, хрустящий' },
    { name: 'Зозуля', days: 45, desc: 'Длинноплодный, теплица' },
    { name: 'Конкурент', days: 48, desc: 'Для засолки' },
    { name: 'Кураж', days: 42, desc: 'Партенокарпик, урожайный' },
    { name: 'Засолочный', days: 50, desc: 'Крепкий, хрустящий' },
    { name: 'Китайский длинный', days: 55, desc: 'До 40 см, теплица' },
    { name: 'Изящный', days: 45, desc: 'Открытый грунт, неприхотливый' },
    { name: 'Директор', days: 40, desc: 'Ранний, партенокарпик' },
  ],
  carrot: [
    { name: 'Нантская', days: 65, desc: 'Классическая, цилиндрическая' },
    { name: 'Шантенэ', days: 75, desc: 'Конусовидная, хранится долго' },
    { name: 'Лосиноостровская', days: 80, desc: 'Сладкая, хранение' },
    { name: 'Каротель', days: 60, desc: 'Короткая, ранняя' },
    { name: 'Витаминная 6', days: 75, desc: 'Высокое содержание каротина' },
    { name: 'Самсон', days: 70, desc: 'Голландская, выровненная' },
    { name: 'Флаккэ', days: 80, desc: 'Длинная, до 25 см' },
    { name: 'Тушон', days: 65, desc: 'Короткая, для тяжёлых почв' },
    { name: 'Абако', days: 70, desc: 'Гибрид, устойчивый' },
    { name: 'Курода', days: 75, desc: 'Японская, сладкая' },
  ],
  potato: [
    { name: 'Импала', days: 60, desc: 'Ранний, жёлтая мякоть' },
    { name: 'Ривьера', days: 55, desc: 'Сверхранний' },
    { name: 'Невский', days: 80, desc: 'Классика, белая мякоть' },
    { name: 'Синеглазка', days: 80, desc: 'Народный сорт, вкусный' },
    { name: 'Розара', days: 75, desc: 'Розовая кожура, рассыпчатый' },
    { name: 'Ред Скарлет', days: 70, desc: 'Красный, ранний' },
    { name: 'Пикассо', days: 90, desc: 'Пятнистая кожура, хранение' },
    { name: 'Удача', days: 65, desc: 'Ранний, урожайный' },
    { name: 'Колобок', days: 80, desc: 'Круглый, лёжкий' },
    { name: 'Голубизна', days: 85, desc: 'Поздний, хранение' },
  ],
  pepper: [
    { name: 'Калифорнийское чудо', days: 95, desc: 'Крупный, сладкий' },
    { name: 'Ласточка', days: 100, desc: 'Конусовидный, сочный' },
    { name: 'Богатырь', days: 110, desc: 'Крупноплодный' },
    { name: 'Белозёрка', days: 90, desc: 'Молочно-белый, нежный' },
    { name: 'Купец', days: 95, desc: 'Урожайный гибрид' },
    { name: 'Геракл', days: 105, desc: 'Красный, толстостенный' },
    { name: 'Какаду', days: 100, desc: 'Длинный, желтеет' },
    { name: 'Оранжевое чудо', days: 95, desc: 'Оранжевый, витаминный' },
    { name: 'Тёща', days: 90, desc: 'Острый, для маринования' },
    { name: 'Гогошары', days: 100, desc: 'Томатовидный, сладкий' },
  ],
  cabbage: [
    { name: 'Июньская', days: 60, desc: 'Ранняя, нежная' },
    { name: 'Слава', days: 85, desc: 'Средняя, для засолки' },
    { name: 'Амагер', days: 120, desc: 'Поздняя, хранение' },
    { name: 'Московская поздняя', days: 130, desc: 'Зимнее хранение' },
    { name: 'Белорусская', days: 100, desc: 'Средняя, универсальная' },
    { name: 'Мегатон', days: 90, desc: 'Гибрид, крупные кочаны' },
    { name: 'Краутман', days: 95, desc: 'Немецкий, для квашения' },
    { name: 'Агрессор', days: 115, desc: 'Поздний, устойчивый' },
    { name: 'Колобок', days: 110, desc: 'Круглый, плотный' },
    { name: 'Атрия', days: 105, desc: 'Гибрид, лёжкий' },
  ],
  onion: [
    { name: 'Штутгартер', days: 75, desc: 'Немецкий, плоский' },
    { name: 'Эксибишен', days: 90, desc: 'Гигантский, сладкий' },
    { name: 'Центурион', days: 80, desc: 'Гибрид, лёжкий' },
    { name: 'Ред Барон', days: 75, desc: 'Красный, сладкий' },
    { name: 'Стригуновский', days: 70, desc: 'Острый, народный' },
    { name: 'Бессоновский', days: 65, desc: 'Местный, лёжкий' },
    { name: 'Геркулес', days: 80, desc: 'Крупный, урожайный' },
    { name: 'Золотистый Семко', days: 85, desc: 'Гибрид, транспортный' },
    { name: 'Мячковский', days: 75, desc: 'Полуострый, хранение' },
    { name: 'Халцедон', days: 80, desc: 'Жёлтый, лёжкий' },
  ],
  strawberry: [
    { name: 'Клери', days: 30, desc: 'Ранняя, итальянская' },
    { name: 'Азия', days: 35, desc: 'Ранняя, крупная' },
    { name: 'Альба', days: 28, desc: 'Очень ранняя' },
    { name: 'Хоней', days: 35, desc: 'Американская, сладкая' },
    { name: 'Эльсанта', days: 40, desc: 'Голландская, транспортная' },
    { name: 'Полка', days: 45, desc: 'Поздняя, ароматная' },
    { name: 'Зефир', days: 38, desc: 'Крупная, розовая' },
    { name: 'Мальвина', days: 50, desc: 'Поздняя, устойчивая' },
    { name: 'Флоренс', days: 45, desc: 'Позднеспелая, британская' },
    { name: 'Королева Елизавета', days: 30, desc: 'Ремонтантная' },
  ],
  zucchini: [
    { name: 'Цукеша', days: 45, desc: 'Цилиндрический, тёмный' },
    { name: 'Аэронавт', days: 42, desc: 'Ранний, компактный' },
    { name: 'Белый', days: 48, desc: 'Белоплодный, нежный' },
    { name: 'Желтоплодный', days: 45, desc: 'Декоративный, вкусный' },
    { name: 'Искандер', days: 40, desc: 'Гибрид, партенокарпик' },
    { name: 'Ролик', days: 45, desc: 'Круглый, для фарширования' },
    { name: 'Грибовский', days: 50, desc: 'Классика, неприхотливый' },
    { name: 'Квета', days: 42, desc: 'Чешский, урожайный' },
    { name: 'Чёрный красавец', days: 44, desc: 'Тёмно-зелёный, сочный' },
    { name: 'Арал', days: 40, desc: 'Гибрид, ультраранний' },
  ],
}

// ============= Лимиты культур по тарифам =============
export const PLAN_LIMITS: Record<Plan, number> = {
  free: 10,
  base: 15,
  pro: 999,
}
