create table if not exists public.garden_data (
  id bigint generated by default as identity primary key,
  vk_user_id bigint not null unique,
  onboarding jsonb not null default '{}'::jsonb,
  plan text not null default 'free',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.diary (
  id bigint generated by default as identity primary key,
  vk_user_id bigint not null,
  crop_id text,
  operation text,
  text text not null,
  created_at timestamptz not null default now()
);

create index if not exists diary_vk_user_id_created_at_idx
  on public.diary (vk_user_id, created_at desc);

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  vk_user_id bigint not null,
  year integer not null,
  snapshot jsonb not null default '{}'::jsonb,
  summary text,
  created_at timestamptz not null default now(),
  unique (vk_user_id, year)
);

create index if not exists seasons_vk_user_id_year_idx
  on public.seasons (vk_user_id, year desc);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  vk_user_id bigint not null,
  type text,
  title text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists notifications_vk_user_id_created_at_idx
  on public.notifications (vk_user_id, created_at desc);
