create table if not exists public.billing_payments (
  id bigint generated by default as identity primary key,
  provider text not null default 'yookassa',
  provider_payment_id text not null unique,
  vk_user_id bigint not null,
  offer_id text not null,
  plan text not null,
  period text not null,
  amount numeric(10,2) not null,
  currency text not null default 'RUB',
  status text not null,
  payment_method_id text,
  metadata jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists billing_payments_vk_user_id_created_at_idx
  on public.billing_payments (vk_user_id, created_at desc);
