create table if not exists public.api_usage (
  id bigint generated by default as identity primary key,
  service text not null,
  endpoint text,
  calls integer not null default 0,
  errors integer not null default 0,
  date date not null default current_date,
  created_at timestamptz not null default now(),
  unique (service, endpoint, date)
);
