create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  vk_user_id bigint not null,
  event_type text not null,
  source text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_vk_user_id_created_at_idx
  on public.analytics_events (vk_user_id, created_at desc);

create index if not exists analytics_events_type_created_at_idx
  on public.analytics_events (event_type, created_at desc);
