-- Очередь уведомлений для масштабируемого fan-out
-- Сейчас не используется, включается заменой одной переменной

create table if not exists public.notification_jobs (
  id bigint generated by default as identity primary key,
  vk_user_id bigint not null,
  job_type text not null default 'morning_advice',
  status text not null default 'pending', -- pending | processing | done | failed
  attempts integer not null default 0,
  scheduled_for timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists notif_jobs_status_scheduled_idx
  on public.notification_jobs (status, scheduled_for)
  where status = 'pending';

create index if not exists notif_jobs_vk_user_created_idx
  on public.notification_jobs (vk_user_id, created_at desc);

-- Enable RLS
alter table public.notification_jobs enable row level security;
-- Only service_role can access (no anon policies)
